"""
Django settings for gymReview project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Config, RepositoryEnv
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configure decouple to look for .env file in the Backend directory
config = Config(RepositoryEnv(os.path.join(BASE_DIR.parent, '.env')))

# GDAL configuration for different platforms
if os.name == 'nt':  # Windows
    OSGEO4W = r"C:\OSGeo4W"
    if 'OSGEO4W_ROOT' not in os.environ:
        os.environ['OSGEO4W_ROOT'] = OSGEO4W
        os.environ['GDAL_DATA'] = OSGEO4W + r"\share\gdal"
        os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
        os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']
    GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal310.dll'
    GEOS_LIBRARY_PATH = r'C:\OSGeo4W\bin\geos_c.dll'
else:  # Linux/Docker - try to find dynamically
    import glob
    import subprocess
    
    # First, try environment variable
    gdal_env = os.getenv('GDAL_LIBRARY_PATH', '').strip()
    if gdal_env and os.path.exists(gdal_env):
        GDAL_LIBRARY_PATH = gdal_env
    else:
        # Try to find GDAL library in common locations
        gdal_paths = []
        # Check common Linux library paths
        for pattern in [
            '/usr/lib/x86_64-linux-gnu/libgdal.so*',
            '/usr/lib/aarch64-linux-gnu/libgdal.so*',
            '/usr/lib/*/libgdal.so*',
            '/usr/local/lib/libgdal.so*'
        ]:
            gdal_paths.extend(glob.glob(pattern))
        
        # Also try using find command if glob doesn't work
        if not gdal_paths:
            try:
                result = subprocess.run(
                    ['find', '/usr/lib', '-name', 'libgdal.so*', '-type', 'f'],
                    capture_output=True,
                    text=True,
                    timeout=5
                )
                if result.returncode == 0:
                    gdal_paths = [p.strip() for p in result.stdout.split('\n') if p.strip()]
            except:
                pass
        
        # Use first found path, or try hardcoded paths
        if gdal_paths:
            GDAL_LIBRARY_PATH = sorted(gdal_paths)[0]  # Prefer .so over .so.X versions
        elif os.path.exists('/usr/lib/x86_64-linux-gnu/libgdal.so'):
            GDAL_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libgdal.so'
        elif os.path.exists('/usr/lib/aarch64-linux-gnu/libgdal.so'):
            GDAL_LIBRARY_PATH = '/usr/lib/aarch64-linux-gnu/libgdal.so'
        else:
            # macOS fallback
            GDAL_LIBRARY_PATH = '/opt/homebrew/lib/libgdal.dylib'
    
    # Find GEOS library
    geos_paths = []
    for pattern in [
        '/usr/lib/x86_64-linux-gnu/libgeos_c.so*',
        '/usr/lib/aarch64-linux-gnu/libgeos_c.so*',
        '/usr/lib/*/libgeos_c.so*',
        '/usr/local/lib/libgeos_c.so*'
    ]:
        geos_paths.extend(glob.glob(pattern))
    
    if geos_paths:
        GEOS_LIBRARY_PATH = sorted(geos_paths)[0]
    elif os.path.exists('/usr/lib/x86_64-linux-gnu/libgeos_c.so'):
        GEOS_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libgeos_c.so'
    elif os.path.exists('/usr/lib/aarch64-linux-gnu/libgeos_c.so'):
        GEOS_LIBRARY_PATH = '/usr/lib/aarch64-linux-gnu/libgeos_c.so'
    else:
        GEOS_LIBRARY_PATH = '/opt/homebrew/lib/libgeos_c.dylib'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-kzmwd)6%ijy&ma659n5%ix5)@(oe^_!8&-eqznqmxk!-v3sra4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# API Keys
GOOGLE_PLACES_API_KEY = config('GOOGLE_PLACES_API_KEY', default='')

# Development mode - when True, uses database-only search (no Google API calls)
# This helps avoid API charges during development
USE_DB_ONLY_MODE = config('USE_DB_ONLY_MODE', default=False, cast=bool)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = config('AWS_REGION', default='us-east-1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # Add GIS support
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'gymapp',
]

# Custom user model
AUTH_USER_MODEL = 'gymapp.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gymReview.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gymReview.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration
# For development, use SQLite (easier setup)
# For production, use PostgreSQL with PostGIS
if config('USE_POSTGRES', default='False').lower() == 'true' or os.getenv('POSTGRES_HOST'):
    # Use PostgreSQL with PostGIS (for Docker or production)
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': os.getenv('POSTGRES_DB', config('POSTGRES_DB', default='gymapp')),
            'USER': os.getenv('POSTGRES_USER', config('POSTGRES_USER', default='gymapp_user')),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', config('POSTGRES_PASSWORD', default='')),
            'HOST': os.getenv('POSTGRES_HOST', config('POSTGRES_HOST', default='localhost')),
            'PORT': os.getenv('POSTGRES_PORT', config('POSTGRES_PORT', default='5432')),
        }
    }
else:
    # Use SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
# Use environment variable for MEDIA_ROOT in production (Docker), fallback to BASE_DIR/media for development
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))
# Ensure MEDIA_ROOT is a Path object
if isinstance(MEDIA_ROOT, str):
    MEDIA_ROOT = Path(MEDIA_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

CORS_ALLOW_CREDENTIALS = True

# Email settings (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
DEFAULT_FROM_EMAIL = 'noreply@gymreview.com'
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'your-smtp-host'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email'
# EMAIL_HOST_PASSWORD = 'your-password'

# Frontend URL for password reset links
FRONTEND_URL = 'http://localhost:3000'  # Update this for production

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule (for periodic tasks)
CELERY_BEAT_SCHEDULE = {
    'promote-amenities-nightly': {
        'task': 'gymapp.tasks.promote_amenities_task',
        'schedule': crontab(hour=2, minute=0),  # 2 AM daily
    },
    'update-user-reputations-daily': {
        'task': 'gymapp.tasks.update_user_reputations_task',
        'schedule': crontab(hour=1, minute=0),  # 1 AM daily
    },
}
