# Generated by Django 5.1.7 on 2025-10-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_amenitycategory_user_account_age_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='programs_classes_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
            preserve_default=False,
        ),
    ]
