# Generated by Django 5.1.7 on 2025-10-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_review_programs_classes_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
