# Generated by Django 5.1.7 on 2025-10-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_alter_gym_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='place_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
