# Generated by Django 5.1.7 on 2025-10-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_alter_gym_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='photo_reference',
            field=models.CharField(blank=True),
        ),
    ]
