# Generated by Django 5.1.7 on 2025-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_alter_gym_photo_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='data_source',
            field=models.CharField(choices=[('places_api', 'Google Places API'), ('user_generated', 'User Generated'), ('manual', 'Manual Entry')], default='places_api', max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='last_places_api_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
