# Generated by Django 5.1.7 on 2025-10-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_gym_data_source_gym_last_places_api_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('tile_radius', models.IntegerField()),
                ('results_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gym_review_tile_cache',
                'indexes': [models.Index(fields=['cache_key'], name='gym_review__cache_k_4e659d_idx'), models.Index(fields=['expires_at'], name='gym_review__expires_97078c_idx')],
            },
        ),
    ]
