# Generated by Django 5.1.7 on 2025-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_tilecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='photo_references',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
