# Generated by Django 5.1.7 on 2025-11-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_gym_photo_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If True, this review will be shown as anonymous'),
        ),
    ]
