# Generated by Django 5.1.7 on 2025-11-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_review_is_anonymous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'gym')},
        ),
    ]
