# Generated by Django 5.1.7 on 2025-11-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymphoto',
            name='review',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this photo to a specific review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gymapp.review'),
        ),
    ]
